package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"fmt"
	"msoft/g1/gqlapi/internal/clients/comment"
	"msoft/g1/gqlapi/internal/graph/modelgen"
)

// CommentCreate is the resolver for the commentCreate field.
func (r *mutationResolver) CommentCreate(ctx context.Context, input comment.CreateInput) (*modelgen.CommentCreatePayload, error) {
	panic(fmt.Errorf("not implemented: CommentCreate - commentCreate"))
}

// CommentUpdate is the resolver for the commentUpdate field.
func (r *mutationResolver) CommentUpdate(ctx context.Context, id string, input comment.UpdateInput) (*modelgen.CommentUpdatePayload, error) {
	panic(fmt.Errorf("not implemented: CommentUpdate - commentUpdate"))
}

// CommentDelete is the resolver for the commentDelete field.
func (r *mutationResolver) CommentDelete(ctx context.Context, id string) (*modelgen.CommentDeletePayload, error) {
	panic(fmt.Errorf("not implemented: CommentDelete - commentDelete"))
}

// Comment is the resolver for the comment field.
func (r *queryResolver) Comment(ctx context.Context, id string) (*comment.Comment, error) {
	panic(fmt.Errorf("not implemented: Comment - comment"))
}

// Comments is the resolver for the comments field.
func (r *queryResolver) Comments(ctx context.Context) ([]*comment.Comment, error) {
	panic(fmt.Errorf("not implemented: Comments - comments"))
}
