package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"msoft/g1/gqlapi/internal/clients/comment"
	"msoft/g1/gqlapi/internal/graph/modelgen"
)

// CommentCreate is the resolver for the commentCreate field.
func (r *mutationResolver) CommentCreate(ctx context.Context, input comment.CreateInput) (*modelgen.CommentCreatePayload, error) {
	input.AuthorID = "1" // TODO
	cm, err := r.commentClient.Create(&input)
	if err != nil {
		return &modelgen.CommentCreatePayload{Error: &modelgen.Error{Message: err.Error()}}, nil
	}
	return &modelgen.CommentCreatePayload{Comment: cm}, nil
}

// CommentUpdate is the resolver for the commentUpdate field.
func (r *mutationResolver) CommentUpdate(ctx context.Context, id int, input comment.UpdateInput) (*modelgen.CommentUpdatePayload, error) {
	cm, err := r.commentClient.Update(id, &input)
	if err != nil {
		return &modelgen.CommentUpdatePayload{Error: &modelgen.Error{Message: err.Error()}}, nil
	}
	return &modelgen.CommentUpdatePayload{Comment: cm}, nil
}

// CommentDelete is the resolver for the commentDelete field.
func (r *mutationResolver) CommentDelete(ctx context.Context, id int) (*modelgen.CommentDeletePayload, error) {
	err := r.commentClient.Delete(id)
	if err != nil {
		return &modelgen.CommentDeletePayload{Error: &modelgen.Error{Message: err.Error()}}, nil
	}
	return &modelgen.CommentDeletePayload{}, nil
}

// Comment is the resolver for the comment field.
func (r *queryResolver) Comment(ctx context.Context, id int) (*comment.Comment, error) {
	cm, err := r.commentClient.GetByID(id)
	if err != nil {
		return nil, err
	}
	return cm, nil
}

// Comments is the resolver for the comments field.
func (r *queryResolver) Comments(ctx context.Context) ([]*comment.Comment, error) {
	cms, err := r.commentClient.GetAll()
	if err != nil {
		return nil, err
	}
	return cms, nil
}
